### ISSUE TITLE
De patiënt kan zijn/haar gegevens invullen

### ISSUE THREAD

**Issue by JasperKohlen** [TurtlSandwich/DreamTeam2.0Proftaak#1]
De patiënt kan bloedsuikerspiegel en koolhydraten registreren per maaltijd.

**Comment by JasperKohlen** [comment]
Requirements:
1. De patiënt kan bloedsuikerspiegel registreren na een prik.
2. De patiënt kan koolhydraten registreren per maaltijd

**Comment by TurtlSandwich** [comment]
Data ingevuld en waarde berekend. Berekende waarde kwam overeen met verwachting
