### ISSUE TITLE
De arts en patiënt kunnen de metingen inzien van de patiënt

### ISSUE THREAD

**Issue by JasperKohlen** [TurtlSandwich/DreamTeam2.0Proftaak#2]
Elke arts heeft meerdere patiënten en kan de metingen van deze patiënten zien. De patiënt kan zijn eigen metingen ook zien. Een patiënt heeft maar 1 arts.

**Comment by JasperKohlen** [comment]
Requirements:
1. Elke arts heeft meerdere patiënten
2. Elke arts kan de gegevens van elke patiënt inzien (als hij toestemming heeft gekregen)
3. De patiënt kan geen gegevens van andere patiënten inzien
4. De patiënt kan zijn eigen gegevens inzien 
5. Een patiënt heeft maximaal 1 arts

**Comment by TurtlSandwich** [comment]
Hoogste prioriteit voor oplevering 28-11
