### ISSUE TITLE
De patiënt krijgt een insuline-advies, na een meting.

### ISSUE THREAD

**Issue by JasperKohlen** [TurtlSandwich/DreamTeam2.0Proftaak#3]
Als een patiënt koolhydraten en bloedsuikerspiegel registreert krijgt hij een advies over hoe veel insuline nodig is. koolhydraten wordt gemeten in kilocalorieën, bloedsuikerspiegel wordt gemeten mg/L

**Comment by JasperKohlen** [comment]
Requirements:
1. Een patiënt krijgt insuline-advies nadat hij de koolhydraten en bloedsuikerspiegel doorgeeft
2. Alle meetwaarden worden doorgestuurd naar de bijbehorende arts
3. Koolhydraten worden geregistreerd in kilocalorieën
4. Bloedsuikerspiegel wordt gemeten in mg/L

**Comment by TurtlSandwich** [comment]
Unit Tests gemaakt, resultaat was ok.
